<a href="https://colab.research.google.com/github/j-5912d/Math_Statistics/blob/main/Hometask_6_Math_Stat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Задание 1

1. Известно, что генеральная совокупность распределена нормально со средним квадратическим отклонением, равным 16. Найти доверительный интервал для оценки математического ожидания a с надежностью 0.95, если выборочная средняя M = 80, а объем выборки n = 256.

In [59]:
from scipy.stats import norm
from scipy.special import ndtri
from statistics import NormalDist
import math
import numpy as np
import scipy.stats as stats

In [4]:
a = 1- 0.05/2

In [24]:
z = norm.ppf(a)
z

1.959963984540054

In [25]:
m = 80
n = 256
sigma = math.sqrt(16)
sigma

4.0

In [23]:
interval_a = round(m - z* sigma/math.sqrt(n), 3)
interval_b = round(m + z* sigma/math.sqrt(n), 3)
print(interval_a, " ;  ", interval_b)

79.51  ;   80.49


# Задание 2

2. В результате 10 независимых измерений некоторой величины X, выполненных с одинаковой точностью, получены опытные данные: 6.9, 6.1, 6.2, 6.8, 7.5, 6.3, 6.4, 6.9, 6.7, 6.1 Предполагая, что результаты измерений подчинены нормальному закону распределения вероятностей, оценить истинное значение величины X при помощи доверительного интервала, покрывающего это значение с доверительной вероятностью 0,95.

In [31]:
array_1 = np.array([6.9, 6.1, 6.2, 6.8, 7.5, 6.3, 6.4, 6.9, 6.7, 6.1])
array_1

array([6.9, 6.1, 6.2, 6.8, 7.5, 6.3, 6.4, 6.9, 6.7, 6.1])

In [28]:
z

1.959963984540054

In [46]:
mean_ar = np.mean(array_1)
mean_ar

6.590000000000001

In [47]:
array_1.mean()

6.590000000000001

In [49]:
disp = np.var(array_1, ddof = 1)
disp

0.2032222222222223

In [69]:
sigma = math.sqrt(disp)
sigma

0.4508017549014448

In [50]:
n = len(array_1)
n

10

In [52]:
a = (1 - 0.95)/2
a

0.025000000000000022

In [62]:
t1 = stats.t.ppf(1 - a, n - 1)
t1

2.2621571627409915

In [70]:
interval_a = mean_ar - t1 * sigma / (np.sqrt(n))

In [71]:
interval_b = mean_ar + t1 * sigma / (np.sqrt(n))

In [72]:
print(interval_a, " ;  ", interval_b)

6.267515851415713  ;   6.912484148584288


# Задание 3

3.Рост дочерей 175, 167, 154, 174, 178, 148, 160, 167, 169, 170 Рост матерей  178, 165, 165, 173, 168, 155, 160, 164, 178, 175 Используя эти данные построить 95% доверительный интервал для разности среднего роста родителей и детей.

In [75]:
d_ar = np.array([175, 167, 154, 174, 178, 148, 160, 167, 169, 170] )
d_ar

array([175, 167, 154, 174, 178, 148, 160, 167, 169, 170])

In [77]:
m_ar = np.array([178, 165, 165, 173, 168, 155, 160, 164, 178, 175])
m_ar

array([178, 165, 165, 173, 168, 155, 160, 164, 178, 175])

In [97]:
a = (1 - 0.95)/2
a

0.025000000000000022

In [79]:
n1 = len (m_ar)
n1

10

In [81]:
n2 = len(d_ar)
n2

10

In [82]:
m1 = m_ar.mean()
m1

168.1

In [84]:
m2 = d_ar.mean()
m2

166.2

In [86]:
delta = abs(m1 - m2)
delta

1.9000000000000057

In [87]:
disp1 = np.var(m_ar, ddof = 1)
disp1

60.10000000000001

In [88]:
sigma1 = math.sqrt(disp1)
sigma1

7.752418977325723

In [89]:
sigma2 = math.sqrt(d_ar.var(ddof = 1))
sigma2

9.542885657214313

In [90]:
disp2 = np.power(sigma2, 2)
disp2

91.06666666666665

In [92]:
disp = disp1 + disp2
disp

151.16666666666666

In [94]:
se = math.sqrt(disp/n1 +disp/n2)
se

5.49848463972878

In [98]:
t = stats.t.ppf(1 - a, n1 - 1 + n2 - 1)
t

2.10092204024096

In [102]:
interval_a = round(delta - t * se, 3)

In [103]:
interval_b = round(delta + t * se, 3)


In [104]:
print(interval_a, " ; ", interval_b)

-9.652  ;  13.452
